//
// Generated file, do not edit! Created by nedtool 5.0 from castalia/src/node/communication/mac/tunableMac/TunableMacPacket.msg.
//

#ifndef __TUNABLEMACPACKET_M_H
#define __TUNABLEMACPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "MacPacket_m.h"
// }}

/**
 * Enum generated from <tt>castalia/src/node/communication/mac/tunableMac/TunableMacPacket.msg:19</tt> by nedtool.
 * <pre>
 * enum TunableMacFrameTypeDef
 * {
 * 
 *     DATA_FRAME = 1;
 *     BEACON_FRAME = 2;
 * }
 * </pre>
 */
enum TunableMacFrameTypeDef {
    DATA_FRAME = 1,
    BEACON_FRAME = 2
};

/**
 * Class generated from <tt>castalia/src/node/communication/mac/tunableMac/TunableMacPacket.msg:24</tt> by nedtool.
 * <pre>
 * packet TunableMacPacket extends MacPacket
 * {
 *     int frameType @enum(TunableMacFrameTypeDef);	//1 byte
 *     int source;		//4 bytes
 *     int destination;	//4 bytes
 * }
 * </pre>
 */
class TunableMacPacket : public ::MacPacket
{
  protected:
    int frameType;
    int source;
    int destination;

  private:
    void copy(const TunableMacPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TunableMacPacket&);

  public:
    TunableMacPacket(const char *name=nullptr, int kind=0);
    TunableMacPacket(const TunableMacPacket& other);
    virtual ~TunableMacPacket();
    TunableMacPacket& operator=(const TunableMacPacket& other);
    virtual TunableMacPacket *dup() const {return new TunableMacPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getFrameType() const;
    virtual void setFrameType(int frameType);
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TunableMacPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TunableMacPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TUNABLEMACPACKET_M_H

