//
// Generated file, do not edit! Created by nedtool 5.0 from wise/src/node/sensorManager/sensorManager/SensorManagerMessage.msg.
//

#ifndef __SENSORMANAGERMESSAGE_M_H
#define __SENSORMANAGERMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "WiseSensorManagerMessage_m.h"
// }}

/**
 * Class generated from <tt>wise/src/node/sensorManager/sensorManager/SensorManagerMessage.msg:34</tt> by nedtool.
 * <pre>
 * message SensorReadingMessage extends WiseSensorManagerMessage
 * {
 *     double sensedValue;
 * }
 * </pre>
 */
class SensorReadingMessage : public ::WiseSensorManagerMessage
{
  protected:
    double sensedValue;

  private:
    void copy(const SensorReadingMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SensorReadingMessage&);

  public:
    SensorReadingMessage(const char *name=nullptr, int kind=0);
    SensorReadingMessage(const SensorReadingMessage& other);
    virtual ~SensorReadingMessage();
    SensorReadingMessage& operator=(const SensorReadingMessage& other);
    virtual SensorReadingMessage *dup() const {return new SensorReadingMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual double getSensedValue() const;
    virtual void setSensedValue(double sensedValue);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SensorReadingMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SensorReadingMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SENSORMANAGERMESSAGE_M_H

