//
// Generated file, do not edit! Created by nedtool 5.0 from wise/src/node/sensorManager/wiseEmptySensorManager/WiseEmptySensorMessage.msg.
//

#ifndef __WISEEMPTYSENSORMESSAGE_M_H
#define __WISEEMPTYSENSORMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "WiseSensorManagerMessage_m.h"
// }}

/**
 * Class generated from <tt>wise/src/node/sensorManager/wiseEmptySensorManager/WiseEmptySensorMessage.msg:20</tt> by nedtool.
 * <pre>
 * message WiseEmptySensorMessage extends WiseSensorManagerMessage
 * {
 *     double randomValue;
 * }
 * </pre>
 */
class WiseEmptySensorMessage : public ::WiseSensorManagerMessage
{
  protected:
    double randomValue;

  private:
    void copy(const WiseEmptySensorMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WiseEmptySensorMessage&);

  public:
    WiseEmptySensorMessage(const char *name=nullptr, int kind=0);
    WiseEmptySensorMessage(const WiseEmptySensorMessage& other);
    virtual ~WiseEmptySensorMessage();
    WiseEmptySensorMessage& operator=(const WiseEmptySensorMessage& other);
    virtual WiseEmptySensorMessage *dup() const {return new WiseEmptySensorMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual double getRandomValue() const;
    virtual void setRandomValue(double randomValue);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WiseEmptySensorMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WiseEmptySensorMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __WISEEMPTYSENSORMESSAGE_M_H

