//
// Generated file, do not edit! Created by nedtool 5.0 from castalia/src/node/application/valueReporting/ValueReportingPacket.msg.
//

#ifndef __VALUEREPORTINGPACKET_M_H
#define __VALUEREPORTINGPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ApplicationPacket_m.h"
// }}

/**
 * Struct generated from castalia/src/node/application/valueReporting/ValueReportingPacket.msg:19 by nedtool.
 */
struct ValueReportData
{
    ValueReportData();
    unsigned short nodeID;
    double locX;
    double locY;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const ValueReportData& a);
void __doUnpacking(omnetpp::cCommBuffer *b, ValueReportData& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ValueReportData& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ValueReportData& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>castalia/src/node/application/valueReporting/ValueReportingPacket.msg:25</tt> by nedtool.
 * <pre>
 * packet ValueReportingDataPacket extends ApplicationGenericDataPacket
 * {
 *     ValueReportData extraData;
 * }
 * </pre>
 */
class ValueReportingDataPacket : public ::ApplicationGenericDataPacket
{
  protected:
    ValueReportData extraData;

  private:
    void copy(const ValueReportingDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ValueReportingDataPacket&);

  public:
    ValueReportingDataPacket(const char *name=nullptr, int kind=0);
    ValueReportingDataPacket(const ValueReportingDataPacket& other);
    virtual ~ValueReportingDataPacket();
    ValueReportingDataPacket& operator=(const ValueReportingDataPacket& other);
    virtual ValueReportingDataPacket *dup() const {return new ValueReportingDataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual ValueReportData& getExtraData();
    virtual const ValueReportData& getExtraData() const {return const_cast<ValueReportingDataPacket*>(this)->getExtraData();}
    virtual void setExtraData(const ValueReportData& extraData);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ValueReportingDataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ValueReportingDataPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __VALUEREPORTINGPACKET_M_H

