//
// Generated file, do not edit! Created by nedtool 5.0 from castalia/src/node/application/ApplicationPacket.msg.
//

#ifndef __APPLICATIONPACKET_M_H
#define __APPLICATIONPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Struct generated from castalia/src/node/application/ApplicationPacket.msg:13 by nedtool.
 */
struct ApplicationInteractionControl_type
{
    ApplicationInteractionControl_type();
    ::omnetpp::opp_string applicationID;
    ::omnetpp::opp_string source;
    ::omnetpp::opp_string destination;
    double RSSI;
    double LQI;
    ::omnetpp::simtime_t timestamp;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const ApplicationInteractionControl_type& a);
void __doUnpacking(omnetpp::cCommBuffer *b, ApplicationInteractionControl_type& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ApplicationInteractionControl_type& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ApplicationInteractionControl_type& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>castalia/src/node/application/ApplicationPacket.msg:22</tt> by nedtool.
 * <pre>
 * packet ApplicationGenericDataPacket
 * {
 *     ApplicationInteractionControl_type applicationInteractionControl;
 *     double data;
 *     int sequenceNumber;
 * }
 * </pre>
 */
class ApplicationGenericDataPacket : public ::omnetpp::cPacket
{
  protected:
    ApplicationInteractionControl_type applicationInteractionControl;
    double data;
    int sequenceNumber;

  private:
    void copy(const ApplicationGenericDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ApplicationGenericDataPacket&);

  public:
    ApplicationGenericDataPacket(const char *name=nullptr, int kind=0);
    ApplicationGenericDataPacket(const ApplicationGenericDataPacket& other);
    virtual ~ApplicationGenericDataPacket();
    ApplicationGenericDataPacket& operator=(const ApplicationGenericDataPacket& other);
    virtual ApplicationGenericDataPacket *dup() const {return new ApplicationGenericDataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual ApplicationInteractionControl_type& getApplicationInteractionControl();
    virtual const ApplicationInteractionControl_type& getApplicationInteractionControl() const {return const_cast<ApplicationGenericDataPacket*>(this)->getApplicationInteractionControl();}
    virtual void setApplicationInteractionControl(const ApplicationInteractionControl_type& applicationInteractionControl);
    virtual double getData() const;
    virtual void setData(double data);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ApplicationGenericDataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ApplicationGenericDataPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __APPLICATIONPACKET_M_H

