//
// Generated file, do not edit! Created by nedtool 5.0 from wise/src/node/application/wiseCameraTrackerTest/WiseCameraTrackerTestMessage.msg.
//

#ifndef __WISECAMERATRACKERTESTMESSAGE_M_H
#define __WISECAMERATRACKERTESTMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "WiseApplicationPacket_m.h"
// }}

/**
 * Class generated from <tt>wise/src/node/application/wiseCameraTrackerTest/WiseCameraTrackerTestMessage.msg:26</tt> by nedtool.
 * <pre>
 * packet WiseCameraTrackerTestMessage extends WiseApplicationPacket
 * {
 *     unsigned long trackingCount;
 *     unsigned int targetID;
 *     double positionX;
 *     double positionY;
 * }
 * </pre>
 */
class WiseCameraTrackerTestMessage : public ::WiseApplicationPacket
{
  protected:
    unsigned long trackingCount;
    unsigned int targetID;
    double positionX;
    double positionY;

  private:
    void copy(const WiseCameraTrackerTestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WiseCameraTrackerTestMessage&);

  public:
    WiseCameraTrackerTestMessage(const char *name=nullptr, int kind=0);
    WiseCameraTrackerTestMessage(const WiseCameraTrackerTestMessage& other);
    virtual ~WiseCameraTrackerTestMessage();
    WiseCameraTrackerTestMessage& operator=(const WiseCameraTrackerTestMessage& other);
    virtual WiseCameraTrackerTestMessage *dup() const {return new WiseCameraTrackerTestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned long getTrackingCount() const;
    virtual void setTrackingCount(unsigned long trackingCount);
    virtual unsigned int getTargetID() const;
    virtual void setTargetID(unsigned int targetID);
    virtual double getPositionX() const;
    virtual void setPositionX(double positionX);
    virtual double getPositionY() const;
    virtual void setPositionY(double positionY);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WiseCameraTrackerTestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WiseCameraTrackerTestMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __WISECAMERATRACKERTESTMESSAGE_M_H

