//
// Generated file, do not edit! Created by nedtool 5.0 from wise/src/node/application/wiseCameraSimplePeriodicTracker/WiseCameraSimplePeriodicTracker.msg.
//

#ifndef __WISECAMERASIMPLEPERIODICTRACKER_M_H
#define __WISECAMERASIMPLEPERIODICTRACKER_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "WiseApplicationPacket_m.h"
	#include "WiseDefinitionsTracking.h"
// }}

/**
 * Class generated from <tt>wise/src/node/application/wiseCameraSimplePeriodicTracker/WiseCameraSimplePeriodicTracker.msg:28</tt> by nedtool.
 * <pre>
 * packet WiseSimplePeriodicTrackerMessage extends WiseApplicationPacket
 * {
 *     unsigned long trackingCount; 			//tracking step counter	
 *     unsigned int targetID; 				// ID of the target
 *     double positionX; 						// x-pos of the target
 *     double positionY;						// y-pos the target
 *     unsigned int TypeNeighbour;// Type of neigbourgs employed
 * }
 * </pre>
 */
class WiseSimplePeriodicTrackerMessage : public ::WiseApplicationPacket
{
  protected:
    unsigned long trackingCount;
    unsigned int targetID;
    double positionX;
    double positionY;
    unsigned int TypeNeighbour;

  private:
    void copy(const WiseSimplePeriodicTrackerMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WiseSimplePeriodicTrackerMessage&);

  public:
    WiseSimplePeriodicTrackerMessage(const char *name=nullptr, int kind=0);
    WiseSimplePeriodicTrackerMessage(const WiseSimplePeriodicTrackerMessage& other);
    virtual ~WiseSimplePeriodicTrackerMessage();
    WiseSimplePeriodicTrackerMessage& operator=(const WiseSimplePeriodicTrackerMessage& other);
    virtual WiseSimplePeriodicTrackerMessage *dup() const {return new WiseSimplePeriodicTrackerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned long getTrackingCount() const;
    virtual void setTrackingCount(unsigned long trackingCount);
    virtual unsigned int getTargetID() const;
    virtual void setTargetID(unsigned int targetID);
    virtual double getPositionX() const;
    virtual void setPositionX(double positionX);
    virtual double getPositionY() const;
    virtual void setPositionY(double positionY);
    virtual unsigned int getTypeNeighbour() const;
    virtual void setTypeNeighbour(unsigned int TypeNeighbour);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WiseSimplePeriodicTrackerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WiseSimplePeriodicTrackerMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __WISECAMERASIMPLEPERIODICTRACKER_M_H

