//
// Generated file, do not edit! Created by nedtool 5.0 from castalia/src/helpStructures/TimerServiceMessage.msg.
//

#ifndef __TIMERSERVICEMESSAGE_M_H
#define __TIMERSERVICEMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>castalia/src/helpStructures/TimerServiceMessage.msg:13</tt> by nedtool.
 * <pre>
 * message TimerServiceMessage
 * {
 *     int timerIndex;
 * }
 * </pre>
 */
class TimerServiceMessage : public ::omnetpp::cMessage
{
  protected:
    int timerIndex;

  private:
    void copy(const TimerServiceMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TimerServiceMessage&);

  public:
    TimerServiceMessage(const char *name=nullptr, int kind=0);
    TimerServiceMessage(const TimerServiceMessage& other);
    virtual ~TimerServiceMessage();
    TimerServiceMessage& operator=(const TimerServiceMessage& other);
    virtual TimerServiceMessage *dup() const {return new TimerServiceMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getTimerIndex() const;
    virtual void setTimerIndex(int timerIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TimerServiceMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TimerServiceMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TIMERSERVICEMESSAGE_M_H

