//
// Generated file, do not edit! Created by nedtool 5.0 from wise/src/node/application/wiseCameraMultiVideo/WiseCameraMultiVideoPacketFull.msg.
//

#ifndef __WISECAMERAMULTIVIDEOPACKETFULL_M_H
#define __WISECAMERAMULTIVIDEOPACKETFULL_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "WiseCameraMultiVideoPacket_m.h"	
	#include <opencv.hpp>
// }}

/**
 * Class generated from <tt>wise/src/node/application/wiseCameraMultiVideo/WiseCameraMultiVideoPacketFull.msg:19</tt> by nedtool.
 * <pre>
 * packet WiseCameraMultiVideoPacketFull extends WiseCameraMultiVideoPacket
 * {
 *     cv::Mat frame; // information matrix of the target estimation by the node
 * }
 * </pre>
 */
class WiseCameraMultiVideoPacketFull : public ::WiseCameraMultiVideoPacket
{
  protected:
    cv::Mat frame;

  private:
    void copy(const WiseCameraMultiVideoPacketFull& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WiseCameraMultiVideoPacketFull&);

  public:
    WiseCameraMultiVideoPacketFull(const char *name=nullptr, int kind=0);
    WiseCameraMultiVideoPacketFull(const WiseCameraMultiVideoPacketFull& other);
    virtual ~WiseCameraMultiVideoPacketFull();
    WiseCameraMultiVideoPacketFull& operator=(const WiseCameraMultiVideoPacketFull& other);
    virtual WiseCameraMultiVideoPacketFull *dup() const {return new WiseCameraMultiVideoPacketFull(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual cv::Mat& getFrame();
    virtual const cv::Mat& getFrame() const {return const_cast<WiseCameraMultiVideoPacketFull*>(this)->getFrame();}
    virtual void setFrame(const cv::Mat& frame);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WiseCameraMultiVideoPacketFull& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WiseCameraMultiVideoPacketFull& obj) {obj.parsimUnpack(b);}


#endif // ifndef __WISECAMERAMULTIVIDEOPACKETFULL_M_H

