// *****************************************************************************
//  Copyright (C): Juan C. SanMiguel, 2015
//  Author(s): Juan C. SanMiguel
//
//  Developed at Queen Mary University of London (UK) & University Autonoma of Madrid (Spain)
//  This file is distributed under the terms in the attached LICENSE_2 file.
//
//  This file is part of the implementation for the MTIC-consensus tracker for multiple targets:
//         Kamal et al, "Distributed Multi-Target Tracking and Data Association in Vision Networks",
//         IEEE TPAMI 2016.
//         http://ieeexplore.ieee.org/document/7286852/
//
//  Updated contact information:
//  - Juan C. SanMiguel - Universidad Autonoma of Madrid - juancarlos.sanmiguel@uam.es
//  - Andrea Cavallaro - Queen Mary University of London - a.cavallaro@qmul.ac.uk
//
// *****************************************************************************
#ifndef __WISECAMERAS_MTIC_H__
#define __WISECAMERAS_MTIC_H__

#include "WiseCameraSimplePeriodicTracker.h"
#include "WiseDefinitionsTracking.h" //include for definitions of states and measurements
#include "WiseCameraMTIC_Msg_m.h"
#include "WiseCameraMTIC_utils.h" //include specific-structures for single-target tracking using ICF (in 'icf' namespace)
#include "mvtnorm.h"

#define MAX_ITER_BUFFER_ICFNN 20

/*! \class WiseCameraMTIC
 *  \brief This class implements distributed multi-target tracking based on Information Consensus Filter
 *
 *  The KCF algorithm has been modified to be used for multi-target tracking by using ground-truth for
 *  associating previous targets and obtained measurements - see function make_measurements()
 *
 *  More details available at "Kamal et al., XXXXX, IEEE PAMI2015"
 */
class WiseCameraMTIC : public WiseCameraSimplePeriodicTracker
{

private:
    static ofstream logger; //!< Used to collect node print-out

        unsigned int dimS; //!< Dimension of the state vector
        unsigned int dimM; //!< Dimension of the measurement vector

        std::vector<mtic::node_ctrl_mtic_t> node_controls; //!< Structure for controlling node's operations

        //Target management
        std::vector<cv::Mat> zlist; //list containing measurements and clutter
        int n_targets;       //!< Number of targets being tracked by the node
        int max_neigb_network; //!< Maximum number of neighbors in the network (connectivity degree)

        //ICF filters for all targets (prior/posterior state & covariance, transition/measurement matrices,...)
        std::vector<mtic::MTIC_t> ICFs;//!< List of ICFs for each target
        float procNoiseCov;            //!< Common process noise covariance (input in .ned)
        float measNoiseCov;            //!< Common measurement noise covariance (input in .ned)

       //Consensus variables (generic for all targets)
    double alpha;               //!< Rate of adaptation of the consensus (input in .ned)
    unsigned long iter_max;    //!< Maximum number of iterations to be done (input in .ned)
    string share;        //!< ...

    std::vector<mtic::mtic_state_t> camStatus;

    //Association MTT variables
    double lambda; //!< clutter per camera sensor (high value --> more clutter measures)
    int countClutters;

    bool collectNetworkStats;
    bool collectPowerStats;
    bool collectAccuracyStats;

public:
    virtual ~WiseCameraMTIC();

protected:
    // Functions to be implemented from WiseCameraSimplePeriodicTracker class
    virtual void at_startup();                       //!< Init internal variables. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual void at_finishSpecific();
    virtual void at_timer_fired(int index);     //!< Response to alarms generated by specific tracker. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual void at_tracker_init();                 //!< Init resources. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual bool at_tracker_first_sample();        //!< Operations at 1st example. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual bool at_tracker_end_first_sample();   //!< Operations at the end of 1st example. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual bool at_tracker_sample();               //!< Operations at the >1st example. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual bool at_tracker_end_sample();          //!< Operations at the end of >1st example. To implement in superclasses of WiseCameraSimplePeriodicTracker.

    // Functions to be implemented from WiseBaseApplication class
    virtual void process_network_message(WiseApplicationPacket *); //!< Processing of packets received from network. To implement in superclasses of WiseBaseApplication.
    virtual void handleDirectApplicationMessage(WiseApplicationPacket *); //!< Processing of packets received from network. To implement in superclasses of WiseBaseApplication.
    virtual void make_measurements(const std::vector<WiseTargetDetection>&);  //!< Conversion of camera detections into ordered lists of measurements for tracking. To implement in superclasses of WiseBaseApplication.

    virtual void handleMacControlMessage(cMessage *);

private:
    void readParameters();
    void initStructures();        //!< Initialization of internal variables&structures.
    int sendICFmessage(int tid);  //!< Send a message to neigbourgs to perfom consensus.
    void logResult(int tid);       //!< Write results in a logfile

    //void dataAssociation();
    void consensusStart(int tid);
    void consensusProcess(int tid, int k);
    void checkNextConsensusRound(int tid, int k);

    void generateClutterMeasurements();

    void dataAssociation();
    double findPd(cv::Mat a, cv::Mat b, WiseCameraInfo::fov_di_t &fov);
};

#endif // __WISECAMERAS_MTIC_H__
