// *****************************************************************************
//  Copyright (C): Juan C. SanMiguel, 2014
//  Author(s): Juan C. SanMiguel
//  Developed at EECS, Queen Mary University (London)
//  This file is distributed under the terms in the attached LICENSE_2 file.  
//  If you do not find this file, copies can be found by writing to:
//  - juan.carlos.sanmiguel@eecs.qmul.ac.uk
//  - andrea.cavallaro@eecs.qmul.ac.uk                                        
// *****************************************************************************

#ifndef __WISECAMERAST_CLUSTER_ICF_H__
#define __WISECAMERAST_CLUSTER_ICF_H__

#include "WiseCameraSimplePeriodicTracker.h"
#include "WiseCameraClusterICFMsg_m.h"
#include "WiseDefinitionsTracking.h" //include for definitions of states and measurements
#include "WiseCameraClusterICF_utils.h" //include specific-structures for single-target tracking using ICF (in 'icf' namespace)

#define MAX_SIZE_BUFFER 10

/*! \class WiseCameraClusterICF
 *  \brief This class implements distributed Single-target tracking based on Information Consensus Filter
 *
 *  The KCF algorithm has been modified to be used for multi-target tracking by using ground-truth for
 *  associating previous targets and obtained measurements - see function make_measurements()
 *
 *  More details available at "Kamal et al., XXXXX, IEEE TAC2013"
 */
class WiseCameraClusterICF : public WiseCameraSimplePeriodicTracker
{

private:
    static ofstream logger; //!< Used to collect node print-out

    unsigned int dimS; //!< Dimension of the state vector
    unsigned int dimM; //!< Dimension of the measurement vector

    std::vector<icfcluster::node_ctrl_t> node_controls; //!< Structure for controlling node's operations

    //Target management
    int n_targets;       //!< Number of targets being tracked by the node
    int max_neigb_network;       //!<
    std::vector<cv::Mat> z;        //!< Measurements obtained at each tracking step   (z_l)
    std::vector<cv::Mat> xgt;      //!< Ground-truth positions of target states (gt_l)
    std::vector<double> error;    //!< Error of the target estimation
    std::vector<double> errorAcc; //!< Error of the target estimation (accumulated)

    //ICF filters for all targets (prior/posterior state & covariance, transition/measurement matrices,...)
    std::vector<icfcluster::ICF_t> ICFs;//!< List of ICFs for each target
    float procNoiseCov;            //!< Common process noise covariance (input in .ned)
    float measNoiseCov;            //!< Common measurement noise covariance (input in .ned)

    //Consensus variables (generic for all targets)
    double alpha;               //!< Rate of adaptation of the consensus (input in .ned)
    unsigned long iter_max;    //!< Maximum number of iterations to be done (input in .ned)

public:
    virtual ~WiseCameraClusterICF();

protected:
    // Functions to be implemented from WiseCameraSimplePeriodicTracker class
    virtual void at_startup();                       //!< Init internal variables. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual void at_finishSpecific() {};
    virtual void at_timer_fired(int index) {} ;     //!< Response to alarms generated by specific tracker. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual void at_tracker_init();                 //!< Init resources. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual bool at_tracker_first_sample();        //!< Operations at 1st example. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual bool at_tracker_end_first_sample();   //!< Operations at the end of 1st example. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual bool at_tracker_sample();               //!< Operations at the >1st example. To implement in superclasses of WiseCameraSimplePeriodicTracker.
    virtual bool at_tracker_end_sample();          //!< Operations at the end of >1st example. To implement in superclasses of WiseCameraSimplePeriodicTracker.

    // Functions to be implemented from WiseBaseApplication class
    virtual void process_network_message(WiseApplicationPacket *); //!< Processing of packets received from network. To implement in superclasses of WiseBaseApplication.
    virtual void handleDirectApplicationMessage(WiseApplicationPacket *); //!< Processing of packets received from network. To implement in superclasses of WiseBaseApplication.
    virtual void make_measurements(const std::vector<WiseTargetDetection>&);  //!< Conversion of camera detections into ordered lists of measurements for tracking. To implement in superclasses of WiseBaseApplication.

private:
    void readParameters();
    void initStructures();        //!< Initialization of internal variables&structures.
    void initKF(int tid);          //!< Initialization of memory for KF variables
    int sendICFmessage(int tid);  //!< Send a message to neigbourgs to perfom consensus.
    void logResult(int tid);       //!< Write results in a logfile

    //void dataAssociation();
    void prepData (int tid);
    void consensusStart(int tid);
    void consensusProcess(int tid, int k);
    void estimate(int tid);

    int findIndexInBuffer(int tid, int iter_index);
    void storeDataInBuffer(int tid, int iter_index, int nodeID, WiseCameraClusterICFMsg *m);
};

#endif // __WISECAMERAST_CLUSTER_ICF_H__
