function [res]=CAWC_compute_energy(root_dir,results_dir)
% This function reads the data generated by the app 'wiseCameraCAWcamTrack'
% and computes the following statistics:
%   - Activation times (e.g. load) for sensing, processing & communications
%   - Energy consumption for each second and frame (cameras)
%   
%   Input arguments:
%   - root_dir: location of the root directory with all experiments
%   - results_dir: location of the directory with the selected experiment
%   Example:
%           root_dir='/home/jcs/code/svn/multicamera/wise-mnet/dev/wise/simulations/wiseCameraCAWcamTrack/';
%           experiment='res_P_t09_7fps_25s_r50_o1';
%           res=CAWC_compute_energy(root_dir,experiment,'pets2009_S2_L1',0);
%   
%   Author:      Juan Carlos SanMiguel (juancarlos.sanmiguel@uam.es)
%   Affiliation: University Autonoma of Madrid
%   URL:         http://www-vpu.ii.uam.es/~jcs
%   Date:        November 2015


%% COMPUTE RESOURCE USAGE
res_cam = CAWC_compute_energy_cams(root_dir,results_dir);
res_coa = CAWC_compute_energy_coalition(root_dir,results_dir);


%% SAVE RESULTS
fprintf('Data saved to %s',['./data/' results_dir '_ResourcesALL.mat']);
save(['./data/' results_dir '_ResourcesALL.mat'],'res_cams', 'res_coa');
