//
// Generated file, do not edit! Created by nedtool 5.0 from wise/src/node/application/wiseCameraAppTest/WiseCameraAppTestPacket.msg.
//

#ifndef __WISECAMERAAPPTESTPACKET_M_H
#define __WISECAMERAAPPTESTPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "WiseApplicationPacket_m.h"
// }}

/**
 * Class generated from <tt>wise/src/node/application/wiseCameraAppTest/WiseCameraAppTestPacket.msg:24</tt> by nedtool.
 * <pre>
 * packet WiseCameraAppTestPacket extends WiseApplicationPacket
 * {
 *     unsigned int detectionCounter;
 * }
 * </pre>
 */
class WiseCameraAppTestPacket : public ::WiseApplicationPacket
{
  protected:
    unsigned int detectionCounter;

  private:
    void copy(const WiseCameraAppTestPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WiseCameraAppTestPacket&);

  public:
    WiseCameraAppTestPacket(const char *name=nullptr, int kind=0);
    WiseCameraAppTestPacket(const WiseCameraAppTestPacket& other);
    virtual ~WiseCameraAppTestPacket();
    WiseCameraAppTestPacket& operator=(const WiseCameraAppTestPacket& other);
    virtual WiseCameraAppTestPacket *dup() const {return new WiseCameraAppTestPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getDetectionCounter() const;
    virtual void setDetectionCounter(unsigned int detectionCounter);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WiseCameraAppTestPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WiseCameraAppTestPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __WISECAMERAAPPTESTPACKET_M_H

